### ISSUE TITLE
Skipping show beavis and butthead gives the following error

### ISSUE THREAD

**Issue by NjayNL** [BenjV/autosub#24]
Traceback (most recent call last):
  File "/volume1/@appstore/autosub/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/volume1/@appstore/autosub/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/volume1/@appstore/autosub/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/volume1/@appstore/autosub/autosub/WebServer.py", line 90, in skipShow
    return str(tmpl)
  File "/var/packages/python/target/lib/python2.7/site-packages/Cheetah/Template.py", line 1005, in __str__
    rc = getattr(self, mainMethName)()
  File "_volume1__appstore_autosub_interface_templates_config_skipshow_tmpl.py", line 89, in respond
  File "/var/packages/python/target/lib/python2.7/site-packages/Cheetah/Template.py", line 1597, in _handleCheetahInclude
    nestedTemplateClass = compiler.compile(source=source, file=file)
  File "/var/packages/python/target/lib/python2.7/site-packages/Cheetah/Template.py", line 637, in compile
    moduleName = convertTmplPathToModuleName(file)
  File "/var/packages/python/target/lib/python2.7/site-packages/Cheetah/convertTmplPathToModuleName.py", line 20, in convertTmplPathToModuleName
    return splitdrive(tmplPath)[1].translate(_pathNameTransChars)
TypeError: character mapping must return integer, None or unicode

All other shows seem to work fine

**Comment by BenjV** [comment]
Not enough info to work with.
When did this happen?
Put a part of the debuglog here when it happend.

**Comment by NjayNL** [comment]
Solved, did a re-install and all is ok
