### ISSUE TITLE
Not starting at all.

### ISSUE THREAD

**Issue by ikkeenjij36** [BenjV/autosub#26]
Hi afgter updating to 1.2.10 when i start the program from it's site from my syno i get this error message
The server encountered an unexpected condition which prevented it from fulfilling the request.
In addition, the custom error page failed: 
OSError: [Errno 2] No such file or directory

Traceback (most recent call last):
  File "/volume1/@appstore/autosub/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/volume1/@appstore/autosub/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/volume1/@appstore/autosub/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/volume1/@appstore/autosub/autosub/WebServer.py", line 493, in index
    tmpl = PageTemplate(file="interface/templates/mobile/home.tmpl")
  File "/var/packages/python/target/lib/python2.7/site-packages/Cheetah/Template.py", line 1259, in __init__
    self._compile(source, file, compilerSettings=compilerSettings)
  File "/var/packages/python/target/lib/python2.7/site-packages/Cheetah/Template.py", line 1545, in _compile
    file = self.serverSidePath(file)
  File "/var/packages/python/target/lib/python2.7/site-packages/Cheetah/Servlet.py", line 42, in serverSidePath
    return normpath(abspath(path.replace("\\", '/')))
  File "/var/packages/python/target/lib/python2.7/posixpath.py", line 364, in abspath
    cwd = os.getcwd()
OSError: [Errno 2] No such file or directory``
When i try to start it from console i get this error `message:
`/var/packages/autosub/scripts/start-stop-status start
/var/packages/python/target/bin/python: can't open file '/AutoSub.py': [Errno 2] No such file or directory
`
How to solve this?
  
  After reinstalling it works half,still it says it can't verify to tvdb and addic7ed and opensubtitles doesn;t get tested as well,keep seeing a circle going round and round

**Comment by ikkeenjij36** [comment]
ok thnx and solved.
