### ISSUE TITLE
Twitter not working on synology nas 

### ISSUE THREAD

**Issue by kboeckx** [BenjV/autosub#43]
Hi,

I'm getting this error message while clicking the button "register twitter". 

Traceback (most recent call last):
  File "/volume1/@appstore/autosub/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/volume1/@appstore/autosub/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/volume1/@appstore/autosub/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/volume1/@appstore/autosub/autosub/WebServer.py", line 423, in regTwitter
    import oauth2
ImportError: No module named oauth2

**Comment by BenjV** [comment]
Ok I will fix that in the next release.
