### ISSUE TITLE
[Synology DS214+] When skipping a show, I get this error

### ISSUE THREAD

**Issue by pven** [BenjV/autosub#44]
When I click on 'Skip Show' I get the error below (in some kind of popup-window)

```
Traceback (most recent call last):
  File "/volume1/@appstore/autosub/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/volume1/@appstore/autosub/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/volume1/@appstore/autosub/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/volume1/@appstore/autosub/autosub/WebServer.py", line 97, in skipShow
    x = literal_eval(x)
  File "/var/packages/python/target/lib/python2.7/ast.py", line 49, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/var/packages/python/target/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    -
    ^
SyntaxError: unexpected EOF while parsing
```

Version is 1.2.23

Can I fix this?

**Comment by BenjV** [comment]
I have no idea.
I cannot reproduce this problem at the moment.

I rewrote the whole Skip Show module because it was very crappy full of bugs so in the next release this will probably be fixed.
So maybe just wait for the next release?

**Comment by pven** [comment]
I will, thx. Lets close this one.
