### ISSUE TITLE
AutoSub.py options seems to be broken

### ISSUE THREAD

**Issue by l-t-k** [BenjV/autosub#46]
The -c option  isn't working and the -h or --help throws:

Traceback (most recent call last):
  File "AutoSub.py", line 135, in <module>
    exit(main())
  File "AutoSub.py", line 75, in main
    raise Usage(help_message)
__main__.Usage

Command used: python AutoSub.py -h

**Comment by BenjV** [comment]
It's a bug.
Will be corrected in the next release op autosub.

**Comment by l-t-k** [comment]
Ok, thanks.

Any idea how I can give this manually?

**Comment by BenjV** [comment]
You have to make some changes to the file AutoSub.py.
For the help message chnage line 75:

>            raise Usage(help_message)


into:

>            raise SystemExit(help_message)


And to correct the config option, change the empty line 126 into this one.

>     autosub.CONFIGFILE = WriteConf


Be carefull to add the right amount of spaces in from of the code, Python is position dependent and also capital sensitive.
